services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: url-shortener-db
      POSTGRES_USER: jonas
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jonas -d url-shortener-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/url-shortener-db
      QUARKUS_DATASOURCE_USERNAME: jonas
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: